default_language_version:
  python: python3.8

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
    - id: stylefix
      name: stylefix
      entry: |
        make codestyle
      language: system

  - repo: local
    hooks:
    - id: stylechecks
      name: stylechecks
      entry: |
        make check-codestyle
      language: system

  - repo: local
    hooks:
    - id: todo-checker
      name: todo-checker
      entry: todo_checker.sh
      language: script
