# This file contains values from Cookiecutter

default_context:
  project_name: "pydastic"
  project_description: "Pydastic is an elasticsearch python ORM based on Pydantic."
  organization: "pydastic"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "pydastic"
  email: "rami.awar.ra@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
